#!/usr/bin/env python3
from collections import namedtuple
from pathlib import Path
import re


Face = namedtuple("Face", ["n0", "n1", "zone_id", "zone_name", "bc"])


def cas_int(text):
    return int(text, 16)


def parse_zone_names(text):
    names = {}
    for zone_id, name in re.findall(r"\(45\s+\(\s*([0-9a-fA-F]+)\s+([^\s()]+)", text):
        names[cas_int(zone_id)] = name.lower()
    return names


def parse_nodes(text):
    nodes = {}
    blocks = re.findall(
        r"\(10\s+\(\s*([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+"
        r"([0-9a-fA-F]+)\s+\d+\s+([0-9a-fA-F]+)\s*\)\s*\((.*?)\)\s*\)",
        text,
        re.S,
    )
    for zone_id, first, last, ndim, data in blocks:
        if cas_int(zone_id) == 0:
            continue
        first = cas_int(first)
        last = cas_int(last)
        ndim = cas_int(ndim)
        values = [float(v) for v in data.split()]
        for node_id, i in zip(range(first, last + 1), range(0, len(values), ndim)):
            nodes[node_id] = (values[i], values[i + 1])
    return nodes


def parse_boundary_faces(text, zone_names, bc_by_zone):
    faces = []
    blocks = re.findall(
        r"\(13\s+\(\s*([0-9a-fA-F]+)\s+[0-9a-fA-F]+\s+"
        r"[0-9a-fA-F]+\s+\d+\s+\d+\s*\)\s*\((.*?)\)\s*\)",
        text,
        re.S,
    )
    for zone_id, data in blocks:
        zone_id = cas_int(zone_id)
        if zone_id == 0:
            continue
        zone_name = zone_names.get(zone_id, "")
        if zone_name not in bc_by_zone:
            continue
        for line in data.splitlines():
            parts = line.split()
            if len(parts) < 4:
                continue
            n0, n1, c0, c1 = [cas_int(v) for v in parts[:4]]
            if c0 == 0 or c1 == 0:
                faces.append(Face(n0, n1, zone_id, zone_name, bc_by_zone[zone_name]))
    return faces


def order_boundary_faces(faces):
    face_by_edge = {}
    next_nodes = {}
    for face in faces:
        edge = frozenset((face.n0, face.n1))
        face_by_edge[edge] = face
        next_nodes.setdefault(face.n0, []).append(face.n1)
        next_nodes.setdefault(face.n1, []).append(face.n0)

    start = min(next_nodes)
    prev = None
    current = start
    ordered = []
    used = set()

    while True:
        candidates = [node for node in next_nodes[current] if node != prev]
        next_node = candidates[0]
        edge = frozenset((current, next_node))
        if edge in used:
            break
        face = face_by_edge[edge]
        ordered.append(Face(current, next_node, face.zone_id, face.zone_name, face.bc))
        used.add(edge)
        prev, current = current, next_node
        if current == start:
            break

    return ordered


def signed_area(faces, nodes):
    area = 0.0
    for face in faces:
        x0, y0 = nodes[face.n0]
        x1, y1 = nodes[face.n1]
        area += x0 * y1 - x1 * y0
    return 0.5 * area


def write_bound_in(output_file, faces, nodes):
    lines = ["# Generated by cas_to_bound.py", "# L x0 y0 x1 y1 dir bc bcnum"]
    last_zone = None
    for face in faces:
        if face.zone_id != last_zone:
            lines.append(f"# Zone {face.zone_id}: {face.zone_name}")
            last_zone = face.zone_id
        x0, y0 = nodes[face.n0]
        x1, y1 = nodes[face.n1]
        lines.append(
            f"L {x0:.16e} {y0:.16e} {x1:.16e} {y1:.16e} 1 {face.bc} 1"
        )
    output_file.write_text("\n".join(lines) + "\n")


def main():
    cas_filename = "test.cas"
    afmgen_dir = Path(".")
    cas_file = afmgen_dir / cas_filename
    output_file = afmgen_dir / "bound.in"

    # Assumptions:
    # - Input is a 2-D ASCII Pointwise/Fluent .cas file.
    # - Grid has one external boundary loop and no holes.
    # - Boundary zones are the expected Pointwise zones below.
    # - Output uses one AFMGEN L segment per CAS boundary face.
    # - No circles, arcs, parabolas, or line merging are attempted.
    expected_boundary_zones = [
        ("symmetry", -8),
        ("pressure-far-field", -2),
        ("wall", -1),
        ("pressure-outlet", -4),
    ]
    bc_by_zone = dict(expected_boundary_zones)

    text = cas_file.read_text()
    zone_names = parse_zone_names(text)
    nodes = parse_nodes(text)
    faces = parse_boundary_faces(text, zone_names, bc_by_zone)
    faces = order_boundary_faces(faces)

    if signed_area(faces, nodes) < 0:
        faces = [Face(f.n1, f.n0, f.zone_id, f.zone_name, f.bc) for f in reversed(faces)]

    write_bound_in(output_file, faces, nodes)
    print(f"Wrote {len(faces)} line segments to {output_file}")


if __name__ == "__main__":
    main()
